function compileAndClose(compId,compId1,Id,height){
		
		if(Id==1){
			$(compId).hide();
			$(compId1).show();
			if(compId==".howToFindMe"){
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo1').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".whetherRecoFriend"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo1').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".myLocation"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo1').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".blacklist"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo1').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".shieldPriLetter"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo1').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".shieldGroupWeibo"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".shieldUserId"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".shieldKeyword"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".shieldSource"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldWeibo').show();$('.shieldWeibo1').hide();	
			}
			if(compId==".shieldWeibo"){
				$('.howToFindMe').show();$('.howToFindMe1').hide();
				$('.whetherRecoFriend').show();$('.whetherRecoFriend1').hide();
				$('.myLocation').show();$('.myLocation1').hide();
				$('.blacklist').show();$('.blacklist1').hide();
				$('.shieldPriLetter').show();$('.shieldPriLetter1').hide();
				$('.shieldGroupWeibo').show();$('.shieldGroupWeibo').hide();
				$('.shieldUserId').show();$('.shieldUserId1').hide();
				$('.shieldKeyword').show();$('.shieldKeyword1').hide();
				$('.shieldSource').show();$('.shieldSource1').hide();	
			}
		}
		if(Id==2){
			$(compId1).hide();
			$(compId).show();	
		}
		if(height==0){$("#wrap").height(650);}
		if(height==1){$("#wrap").height(740);}
		if(height==2||height==3){$("#wrap").height(775);}
		if(height==4||height==5||height==6){$("#wrap").height(937);}
		if(height==7||height==8||height==10){$("#wrap").height(950);}
		if(height==9){$("#wrap").height(1020);}
	}
	
	function whatIsSource(){
		$('.whatIsSource').css("color","blue");	
		$('.pic_whatIsSource').show();
	}
	function closeWhatIsSource(){
		$('.whatIsSource').css("color","black");
		$('.pic_whatIsSource').hide();
	}