function compileAndClose(compId,compId1,Id,height){
		if(Id==1){
			$(compId).hide();
			$(compId1).show();	
			if(compId==".emailAttention"){
				$('.watermakerSet').show();$('.watermakerSet1').hide();
				$('.medalSet').show();$('.medalSet1').hide();
				$('.languageSet').show();$('.languageSet1').hide();
			}
			if(compId==".watermakerSet"){
				$('.emailAttention').show();$('.emailAttention1').hide();
				$('.medalSet').show();$('.medalSet1').hide();
				$('.languageSet').show();$('.languageSet1').hide();
			}
			if(compId==".medalSet"){
				$('.emailAttention').show();$('.emailAttention1').hide();
				$('.watermakerSet').show();$('.watermakerSet1').hide();
				$('.languageSet').show();$('.languageSet1').hide();
			}
			if(compId==".languageSet"){
				$('.emailAttention').show();$('.emailAttention1').hide();
				$('.watermakerSet').show();$('.watermakerSet1').hide();
				$('.medalSet').show();$('.medalSet1').hide();
			}
			
		}	
		if(Id==2){
			$(compId1).hide();
			$(compId).show();		
		}
		if(height==0){$("#wrap").height(550);}
		if(height==1){$("#wrap").height(595);}
		if(height==2){$("#wrap").height(730);}
		if(height==3){$("#wrap").height(630);}
		if(height==4){$("#wrap").height(690);}
	}
