function compileAndClose(compId,compId1,Id,height){
		if(Id==1){
			$(compId).hide();
			$(compId1).show();	
			if(compId==".aiteMe"){
				$('.comment').show();$('.comment1').hide();
				$('.praise').show();$('.praise1').hide();
				$('.privacyLetter').show();$('.privacyLetter1').hide();
				$('.noAttPriLetter').show();$('.noAttPriLetter1').hide();
				$('.newFanse').show();$('.newFanse1').hide();
				$('.friendCircle').show();$('.friendCircle1').hide();
			}
			if(compId==".comment"){
				$('.aiteMe').show();$('.aiteMe1').hide();
				$('.praise').show();$('.praise1').hide();
				$('.privacyLetter').show();$('.privacyLetter1').hide();
				$('.noAttPriLetter').show();$('.noAttPriLetter1').hide();
				$('.newFanse').show();$('.newFanse1').hide();
				$('.friendCircle').show();$('.friendCircle1').hide();
			}
			if(compId==".praise"){
				$('.aiteMe').show();$('.aiteMe1').hide();
				$('.comment').show();$('.comment1').hide();
				$('.privacyLetter').show();$('.privacyLetter1').hide();
				$('.noAttPriLetter').show();$('.noAttPriLetter1').hide();
				$('.newFanse').show();$('.newFanse1').hide();
				$('.friendCircle').show();$('.friendCircle1').hide();
			}
			if(compId==".privacyLetter"){
				$('.aiteMe').show();$('.aiteMe1').hide();
				$('.comment').show();$('.comment1').hide();
				$('.praise').show();$('.praise1').hide();
				$('.noAttPriLetter').show();$('.noAttPriLetter1').hide();
				$('.newFanse').show();$('.newFanse1').hide();
				$('.friendCircle').show();$('.friendCircle1').hide();
			}
			if(compId==".noAttPriLetter"){
				$('.aiteMe').show();$('.aiteMe1').hide();
				$('.comment').show();$('.comment1').hide();
				$('.praise').show();$('.praise1').hide();
				$('.privacyLetter').show();$('.privacyLetter1').hide();
				$('.newFanse').show();$('.newFanse1').hide();
				$('.friendCircle').show();$('.friendCircle1').hide();
			}
			if(compId==".newFanse"){
				$('.aiteMe').show();$('.aiteMe1').hide();
				$('.comment').show();$('.comment1').hide();
				$('.praise').show();$('.praise1').hide();
				$('.privacyLetter').show();$('.privacyLetter1').hide();
				$('.noAttPriLetter').show();$('.noAttPriLetter1').hide();
				$('.friendCircle').show();$('.friendCircle1').hide();
			}
			if(compId==".friendCircle"){
				$('.aiteMe').show();$('.aiteMe1').hide();
				$('.comment').show();$('.comment1').hide();
				$('.praise').show();$('.praise1').hide();
				$('.privacyLetter').show();$('.privacyLetter1').hide();
				$('.noAttPriLetter').show();$('.noAttPriLetter1').hide();
				$('.newFanse').show();$('.newFanse1').hide();
			}
		}	
		if(Id==2){
			$(compId1).hide();
			$(compId).show();		
		}
		if(height==0){$("#wrap").height(550);}
		if(height==1||height==3||height==4){$("#wrap").height(850);}
		if(height==2){$("#wrap").height(1030);}
		if(height==5||height==7){$("#wrap").height(730);}
		if(height==6){$("#wrap").height(760);}
	}